site_name: Dubium
theme:
  name: material


  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.footer
    

  language: en
  palette:
    scheme: slate

copyright: |
  &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">Two Dwo</a>

nav:
  - Início: "index.md"

  - Documentação:
     - Visão Geral do Produto: "visaoAtt.md"
     - Visão Geral do Projeto: "visaoProjeto.md"
     - Proceso de Desenvolvimento de Software: "processoDes.md"
     - Construção de Software: "construcao.md"
     - Lições Aprendidas: "licoesU1.md"
     - Referências Bibliográficas: "refU1.md"

  - Entregas:
    - Unidade 1:
        - Seminário - Processos e Ciclos de Vida: "unidade1-conectafga.md"
        - Vídeo - Apresentação GitPages: "u1-material.md"
    - Unidade 2:
        - Material - Padrões de interface, tipo e estilo de arquitetura: "entrega2-conectafga.md"
        - Vídeo - Apresentação Unidade 2: "entrega2-vdo-conectafga.md"
    - Unidade 3:
        - Material - Construção, CI e Teste: "entrega3-conectafga.md"
        - Vídeo - Apresentação Unidade 3: "entrega3-vdo-conectafga.md"

  - Backlog do Produto:
     - Backlog: "backlog-conectafga.md"
     - MVPs: "mvps2.md"

  - Sprints:
    - Sprint 1:
        - Planning: "sprintConecta/sprint_01/planning.md"
        - Review: "sprintConecta/sprint_01/review.md"
        - Retrospective: "sprintConecta/sprint_01/retrospective.md"
    - Sprint 2:
        - Planning: "sprintConecta/sprint_02/planning.md"
        - Review: "sprintConecta/sprint_02/review.md"
        - Retrospective: "sprintConecta/sprint_02/retrospective.md"
    - Sprint 3:
        - Planning: "sprintConecta/sprint_03/planning.md"
        - Review: "sprintConecta/sprint_03/review.md"
        - Retrospective: "sprintConecta/sprint_03/retrospective.md"

  - Protótipos:
      - MVP1: "prototipos/prototipos-mvp1.md"
      - MVP2: "prototipos/prototipos-mvp2.md"


extra:
  prev_next_buttons: true


markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - toc: {} # adiciona a tabela de conteúdo 
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css